### ISSUE TITLE
Uncaught (in promise): TypeError: WifiWizard2.getConnectedSSID is not a function

### ISSUE THREAD

**Issue by surajrao** [tripflex/WifiWizard2#11]
﻿

### Prerequisites

Check all boxes if you have done the following:
- [x] Checked that your issue isn't already filed: https://github.com/tripflex/wifiwizard2/issues
- [x] Make sure you fill out the Issue Type below

### Issue type
Select all that apply
- [x] Bug
- [ ] Enhancement
- [ ] Task
- [ ] Question
- [ ] Other

### Description

Error in global functions

### Steps to Reproduce

1. Install plugin in Ionic 3 project
2. Use WifiWizard2.getConnectedSSID(success, fail)
Or 
WifiWizard2.getConnectedSSIDAsync()

**Expected behavior:** 

Get success or fail error based on connection [according to Docs](https://github.com/tripflex/WifiWizard2#global-functions).

**Actual behavior:**

ERROR Error: Uncaught (in promise): TypeError: WifiWizard2.getConnectedSSID is not a function
TypeError: WifiWizard2.getConnectedSSID is not a function
    at 8.js:76
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4982)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at 8.js:76
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:4982)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:4973)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at <anonymous>

**Reproduces how often:** 
Everytime.

### Additional Information

According to the [code](https://github.com/tripflex/WifiWizard2/blob/master/www/WifiWizard2.js#L27) it probably needs to be `getCurrentSSID` etc. Either the docs or the js file needs to be updated depending on how you want to keep it.

**Comment by tripflex** [comment]
@surajrao thanks for reporting this, can you please try using the 3.0.0 branch and let me know if you still have issues?

https://github.com/tripflex/WifiWizard2/tree/3.0.0

Note that a lot has changed, so make sure to read the README doc as well:
https://github.com/tripflex/WifiWizard2/blob/3.0.0/README.md

**Comment by tripflex** [comment]
fixed in 5c4a45a9c3da2891fe05a0c406ab99c49e07bee0

**Comment by surajrao** [comment]
@tripflex I think you missed the async version of those methods though. Thanks for the quick response. I created a pull request for it. https://github.com/tripflex/WifiWizard2/pull/12
