### ISSUE TITLE
Main thread blocked while connecting to a network

### ISSUE THREAD

**Issue by Pietfro** [tripflex/WifiWizard2#19]
I have been testing the plugin for the past 3 days and I must say - it is a huge step up in comparison to the previous version:) Good job @tripflex !
However, I am experiencing main thread blockage whenever I run `connect()` method. After `connect()` completes everything goes back to normal.
I am not able to debug the app as everything hangs and CPU goes crazy.

Did anybody notice that as well?

HTC 10
Android 8.0
Cordova 7.0

Same thing happens on Android emulator.

**Comment by touficbatache** [comment]
I have an HTC 10 with Android 8.0 and I'm doing a `WifiWizard2.scan()` with no luck... Can you make this work on your side?

**Comment by tripflex** [comment]
@Pietfro thanks for reporting this, I have seen this happen a few times I just have not had time to figure out why and come up with  a solution ... pretty sure it's just because of the original forked code pieces that are not running in a Runnable ... do you only experience this on `connect` or are there others?  

If this doesn't happen on `scan` then I should be able to resolve this by doing the same as in that method that creates a new Runnable instance

**Comment by Pietfro** [comment]
@tripflex thanks for the response.
I was testing it mostly on `connect` as the app that I am building does not require `scan`. Let me do more thorough testing on other methods and get back to you afterwards.

**Comment by AndreFWeber** [comment]
I am experiencing the same problem on my Android project. I tested it on an Moto g and  Moto g5s plus.  The former (kind of old) freezes while the latter hang for a couple of seconds and then keeps on working.

I had a look on the plugin code and the problem doesn't seem to be on the connect() method itself but on the waitForConnection() one. Maybe the Thread.sleep shouldn't be used there?

But anyway, the temporary FIX for me was to simply comment out line 696 of WifiWizard2.java:

 696       //return waitForConnection(callbackContext, networkIdToConnect);
 697       callbackContext.error("CONNECTION_MECHANISM_DONE");
 698       return true;
 
The downside is that I won't have a callback for successful or failed connection.

**Comment by jack828** [comment]
Hey all. I've fixed this in my PR #43 - @tripflex please could you review and merge if happy :smile:

**Comment by tripflex** [comment]
@jack828 thank you for submitting the PR, i'll respond on the PR

**Comment by JGeraldoLima** [comment]
Still happenning on version 3.0.0 in an Ionic app :/

I'm using an Motorola X Play with Android 7.1.1. Main UI thread keep blocked until the promisse has been returned.
